# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVqmyHyF48Ce34z_gZTQPE3T409as_N8
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("best_model.pkl")
encoder = joblib.load("encoder.pkl")

st.title("💳 Loan Payment Difficulty Prediction")

file = st.file_uploader("Upload CSV file", type="csv")

if file:
    df = pd.read_csv(file)

    st.subheader("Input Data")
    st.dataframe(df.head())

    if st.button("Predict"):

        X = df.copy()

        X = X.drop(columns=["TARGET", "SK_ID_CURR"], errors="ignore")

        # Feature engineering
        if "DAYS_BIRTH" in X.columns:
            X["AGE_YEARS"] = -X["DAYS_BIRTH"] / 365

        if "AMT_CREDIT" in X.columns and "AMT_INCOME_TOTAL" in X.columns:
            X["CREDIT_INCOME_RATIO"] = (
                X["AMT_CREDIT"] / X["AMT_INCOME_TOTAL"]
            )

        for col in X.select_dtypes("number"):
            X[col] = X[col].fillna(X[col].median())

        for col in X.select_dtypes("object"):
            X[col] = X[col].fillna(X[col].mode()[0])
        cat_cols = list(encoder.feature_names_in_)

        for col in cat_cols:
            if col not in X.columns:
                X[col] = ""

        encoded = encoder.transform(X[cat_cols])

        encoded = pd.DataFrame(
            encoded,
            columns=encoder.get_feature_names_out(cat_cols),
            index=X.index
        )

        X = X.drop(columns=cat_cols)
        X = pd.concat([X, encoded], axis=1)

        X = X.reindex(columns=model.feature_names_in_, fill_value=0)

        prediction = model.predict(X)

        result = df.copy()
        result["Prediction"] = prediction

        result["Prediction"] = result["Prediction"].map({
            0: "No Payment Difficulty",
            1: "Payment Difficulty"
        })

        st.subheader("Prediction")
        st.dataframe(result)

        st.success("Prediction completed!")
else:
    st.info("Upload a CSV file to start.")